In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

# ARASAG

## Raw

In [9]:
# Read the AR-ASAG dataset CSV file
arasag_df = pd.read_csv("raw/arasag/AR-ASAG-Dataset.csv")
arasag_df.shape

(2133, 6)

In [38]:
arasag_df.head()

,Answer_ID,Question_Type,Question_Arabic,Model_Arabic,Answer_Arabic,Average_Mark
0,1,عرف المصطلح العلمي,عرف مصطلح الجريمة الإلكترونية,هي كل سلوك غير قانوني يتم باستخدام الأجهزة الإ...,هي سلوك غير أخلاقي يتم عن طريق وسائل الكترونية...,3.000
1,2,عرف المصطلح العلمي,عرف مصطلح الجريمة الإلكترونية,هي كل سلوك غير قانوني يتم باستخدام الأجهزة الإ...,هي كل سلوك غير أخلاقي يتم بواسطة الاجهزة الالك...,5.000
2,3,عرف المصطلح العلمي,عرف مصطلح الجريمة الإلكترونية,هي كل سلوك غير قانوني يتم باستخدام الأجهزة الإ...,هي سلوك غير قانوني يحمل باستعمال الأجهزة الالك...,2.625
3,4,عرف المصطلح العلمي,عرف مصطلح الجريمة الإلكترونية,هي كل سلوك غير قانوني يتم باستخدام الأجهزة الإ...,هي سلوك غير قانوني تستخدم الوسائل الالكترونية ...,4.000
4,5,عرف المصطلح العلمي,عرف مصطلح الجريمة الإلكترونية,هي كل سلوك غير قانوني يتم باستخدام الأجهزة الإ...,هي كل سلوك غير أخلاقي يتم باستخدام الوسائل الا...,3.500

In [40]:
len(arasag_df['Question_Arabic']. value_counts())

48

In [41]:
arasag_df['Average_Mark']. value_counts()

Average_Mark
5.000    169
4.000    169
3.500    138
3.750    136
2.500    134
3.250    124
3.000    121
4.500    116
2.750    107
2.250    103
4.250    100
1.750     91
0.750     86
1.500     81
0.000     80
1.250     74
2.000     71
4.750     67
1.000     55
0.500     48
0.250     26
3.875     13
3.625      7
1.375      4
4.375      3
1.125      2
1.625      2
2.625      1
2.125      1
0.875      1
3.375      1
2.875      1
3.125      1
Name: count, dtype: int64

## Processed

In [10]:
# Read the processed AR-ASAG dataset CSV file
arasag_processed_df = pd.read_csv(r"C:\Users\alvar\Githubs\mentor-eval\data\processed\arasag\arasag_processed.csv")
arasag_processed_df.shape

(2132, 14)

In [11]:
arasag_processed_df.head()

,dataset,exercise_set,question,answer,grade,min_grade,max_grade,subject,exercise_type,isced_level,language,rubric,desired_answer,metadata
0,arasag,10,عرف مصطلح الجريمة الإلكترونية,هي سلوك غير أخلاقي يتم عن طريق وسائل الكترونية...,3,0.0,5.0,cybercrimes,short_answer,6,arabic,NaN,هي كل سلوك غير قانوني يتم باستخدام الأجهزة الإ...,"{""question_type"": ""عرف المصطلح العلمي""}"
1,arasag,10,عرف مصطلح الجريمة الإلكترونية,هي كل سلوك غير أخلاقي يتم بواسطة الاجهزة الالك...,5,0.0,5.0,cybercrimes,short_answer,6,arabic,NaN,هي كل سلوك غير قانوني يتم باستخدام الأجهزة الإ...,"{""question_type"": ""عرف المصطلح العلمي""}"
2,arasag,10,عرف مصطلح الجريمة الإلكترونية,هي سلوك غير قانوني يحمل باستعمال الأجهزة الالك...,3,0.0,5.0,cybercrimes,short_answer,6,arabic,NaN,هي كل سلوك غير قانوني يتم باستخدام الأجهزة الإ...,"{""question_type"": ""عرف المصطلح العلمي""}"
3,arasag,10,عرف مصطلح الجريمة الإلكترونية,هي سلوك غير قانوني تستخدم الوسائل الالكترونية ...,4,0.0,5.0,cybercrimes,short_answer,6,arabic,NaN,هي كل سلوك غير قانوني يتم باستخدام الأجهزة الإ...,"{""question_type"": ""عرف المصطلح العلمي""}"
4,arasag,10,عرف مصطلح الجريمة الإلكترونية,هي كل سلوك غير أخلاقي يتم باستخدام الوسائل الا...,4,0.0,5.0,cybercrimes,short_answer,6,arabic,NaN,هي كل سلوك غير قانوني يتم باستخدام الأجهزة الإ...,"{""question_type"": ""عرف المصطلح العلمي""}"

In [47]:
len(arasag_processed_df['exercise_set']. value_counts())

48

In [48]:
arasag_processed_df['grade']. value_counts()

grade
4    682
2    483
3    356
5    236
1    221
0    154
Name: count, dtype: int64

# Mohler

## Raw

In [11]:
df = pd.read_csv("raw/mohler/mohler_dataset_edited.csv")
df.shape

(2273, 7)

In [12]:
df.head()

,id,question,desired_answer,student_answer,score_me,score_other,score_avg
0,1.1,What is the role of a prototype program in pro...,To simulate the behaviour of portions of the d...,High risk problems are address in the prototyp...,4.0,3.0,3.5
1,1.1,What is the role of a prototype program in pro...,To simulate the behaviour of portions of the d...,To simulate portions of the desired final prod...,5.0,5.0,5.0
2,1.1,What is the role of a prototype program in pro...,To simulate the behaviour of portions of the d...,A prototype program simulates the behaviors of...,5.0,3.0,4.0
3,1.1,What is the role of a prototype program in pro...,To simulate the behaviour of portions of the d...,Defined in the Specification phase a prototype...,5.0,5.0,5.0
4,1.1,What is the role of a prototype program in pro...,To simulate the behaviour of portions of the d...,It is used to let the users have a first idea ...,3.0,3.0,3.0

In [ ]:
# Check how many of the equal scores are integers
equal_scores_mask = df['score_me'] == df['score_other']
equal_scores = df.loc[equal_scores_mask, 'score_me']
integer_equal_scores_count = equal_scores.apply(lambda x: float(x).is_integer()).sum()
integer_equal_scores_count

score_me
5.0    1089
4.0      74
3.0      56
0.0      23
2.0      15
1.0       2
Name: count, dtype: int64

In [16]:
# Do value counts of the integer_equal_scores_count
print(pd.Series([integer_equal_scores_count]).value_counts())

1259    1
Name: count, dtype: int64

In [13]:
print(df.columns.tolist())

['id', 'question', 'desired_answer', 'student_answer', 'score_me', 'score_other', 'score_avg']

## Processed

In [12]:
processed_df = pd.read_csv("processed\mohler\mohler_processed.csv")
processed_df.shape

(1263, 14)

We only took the rows where both evaluators coincided in the grade

In [13]:
processed_df.head()

,dataset,exercise_set,question,answer,grade,min_grade,max_grade,subject,exercise_type,isced_level,language,rubric,desired_answer,metadata
0,mohler,1,What is the role of a prototype program in pro...,To simulate portions of the desired final prod...,5,1.0,5.0,computer_science,short_answer,6,english,NaN,To simulate the behaviour of portions of the d...,NaN
1,mohler,1,What is the role of a prototype program in pro...,Defined in the Specification phase a prototype...,5,1.0,5.0,computer_science,short_answer,6,english,NaN,To simulate the behaviour of portions of the d...,NaN
2,mohler,1,What is the role of a prototype program in pro...,It is used to let the users have a first idea ...,3,1.0,5.0,computer_science,short_answer,6,english,NaN,To simulate the behaviour of portions of the d...,NaN
3,mohler,1,What is the role of a prototype program in pro...,To find problem and errors in a program before...,2,1.0,5.0,computer_science,short_answer,6,english,NaN,To simulate the behaviour of portions of the d...,NaN
4,mohler,1,What is the role of a prototype program in pro...,you can break the whole program into prototype...,5,1.0,5.0,computer_science,short_answer,6,english,NaN,To simulate the behaviour of portions of the d...,NaN

In [14]:
print(processed_df.columns.tolist())

['dataset', 'exercise_set', 'question', 'answer', 'grade', 'min_grade', 'max_grade', 'subject', 'exercise_type', 'isced_level', 'rubric', 'desired_answer', 'metadata']

# ASAP

## Processed

In [14]:
asap_df = pd.read_csv(r"C:\Users\alvar\Githubs\mentor-eval\data\processed\asap\asap_processed.csv")
asap_df.shape

(12977, 14)

In [15]:
asap_df.head()

,dataset,exercise_set,question,answer,grade,min_grade,max_grade,subject,exercise_type,isced_level,language,rubric,desired_answer,metadata
0,asap,1,"More and more people use computers, but not ev...","Dear local newspaper, I think effects computer...",4,1.0,6.0,english,essay_writing,3,english,## Rubric Guidelines\n\n**Score Point 6**: A w...,NaN,NaN
1,asap,1,"More and more people use computers, but not ev...","Dear @CAPS1 @CAPS2, I believe that using compu...",4,1.0,6.0,english,essay_writing,3,english,## Rubric Guidelines\n\n**Score Point 6**: A w...,NaN,NaN
2,asap,1,"More and more people use computers, but not ev...","Dear, @CAPS1 @CAPS2 @CAPS3 More and more peopl...",3,1.0,6.0,english,essay_writing,3,english,## Rubric Guidelines\n\n**Score Point 6**: A w...,NaN,NaN
3,asap,1,"More and more people use computers, but not ev...","Dear Local Newspaper, @CAPS1 I have found that...",5,1.0,6.0,english,essay_writing,3,english,## Rubric Guidelines\n\n**Score Point 6**: A w...,NaN,NaN
4,asap,1,"More and more people use computers, but not ev...","Dear @LOCATION1, I know having computers has a...",4,1.0,6.0,english,essay_writing,3,english,## Rubric Guidelines\n\n**Score Point 6**: A w...,NaN,NaN

In [17]:
asap_df['exercise_set'].value_counts()

exercise_set
5    1805
2    1800
6    1800
1    1783
4    1771
3    1726
7    1569
8     723
Name: count, dtype: int64

# ASAP2

## Processed

In [16]:
asap2_df = pd.read_csv(r"C:\Users\alvar\Githubs\mentor-eval\data\processed\asap2\asap2_processed.csv")
asap2_df.shape

(24728, 14)

In [19]:
asap2_df.head()

,dataset,exercise_set,question,answer,grade,min_grade,max_grade,subject,exercise_type,isced_level,rubric,desired_answer,metadata
0,asap2,3,## Exercise Texts\n\n**The Challenge of Explor...,The author suggests that studying Venus is wor...,4.0,1.0,6.0,english,essay_writing,3,## Rubric\nAfter reading each essay and comple...,NaN,"{""economically_disadvantaged"": ""Economically d..."
1,asap2,3,## Exercise Texts\n\n**The Challenge of Explor...,NASA is fighting to be alble to to go to Venus...,2.0,1.0,6.0,english,essay_writing,3,## Rubric\nAfter reading each essay and comple...,NaN,"{""economically_disadvantaged"": ""Not economical..."
2,asap2,3,## Exercise Texts\n\n**The Challenge of Explor...,"""The Evening Star"", is one of the brightest po...",3.0,1.0,6.0,english,essay_writing,3,## Rubric\nAfter reading each essay and comple...,NaN,"{""economically_disadvantaged"": ""Economically d..."
3,asap2,3,## Exercise Texts\n\n**The Challenge of Explor...,The author supports this idea because from rea...,2.0,1.0,6.0,english,essay_writing,3,## Rubric\nAfter reading each essay and comple...,NaN,"{""economically_disadvantaged"": ""Economically d..."
4,asap2,3,## Exercise Texts\n\n**The Challenge of Explor...,How the author supports this idea is that he s...,2.0,1.0,6.0,english,essay_writing,3,## Rubric\nAfter reading each essay and comple...,NaN,"{""economically_disadvantaged"": ""Economically d..."

In [5]:
asap2_df['exercise_set'].value_counts()

exercise_set
1    6170
2    4883
3    4480
4    3015
5    2175
6    2046
7    1959
Name: count, dtype: int64

# Ellipse

## Raw

In [20]:
ellipse_df = pd.read_csv(r"C:\Users\alvar\Githubs\mentor-eval\data\raw\ellipse\ELLIPSE_Final_github_train.csv")
ellipse_df.shape

(3911, 26)

In [24]:
ellipse_df.head()

,text_id_kaggle,full_text,gender,grade,race_ethnicity,num_words,num_words2,num_words3,num_sent,num_para,num_word_div_para,MTLD,TTR,Type,Token,task,SES,prompt,Overall,Cohesion,Syntax,Vocabulary,Phraseology,Grammar,Conventions,set
0,5661280443,Imagine if you could prove other people that y...,Male,8,Hispanic/Latino,420,431,431,18,4,107.750000,28.626289,25.290023,109,431,Independent,Economically disadvantaged,Benefits of a problem,4.0,3.5,4.0,3.5,3.5,4.0,4.0,train
1,0016926B079C,I think that students would benefit from learn...,Male,12,Black/African American,246,264,261,18,4,65.250000,66.021538,49.621212,131,264,Independent,Economically disadvantaged,Distance learning,3.5,3.5,3.5,3.0,3.0,4.0,3.0,train
2,0022683E9EA5,When a problem is a change you have to let it ...,Female,8,Hispanic/Latino,513,536,533,14,6,88.833333,33.216069,25.373134,136,536,Independent,Not economically disadvantaged,Benefits of a problem,2.5,2.5,2.5,3.0,2.0,2.0,2.5,train
3,00299B378633,"Dear, Principal\n\nIf u change the school poli...",Male,8,Hispanic/Latino,310,330,320,19,2,160.000000,49.329499,34.848485,115,330,Independent,Economically disadvantaged,Grades for extracurricular activities,3.0,3.0,3.5,3.0,3.0,3.0,2.5,train
4,003885A45F42,The best time in life is when you become yours...,Male,12,White,734,757,728,36,8,91.000000,37.516148,26.948481,204,757,Independent,Not economically disadvantaged,Individuality,4.5,4.5,4.5,4.5,4.5,4.0,5.0,train

In [58]:
# Create total_grade column as sum of the 6 scoring dimensions, rounded up to nearest integer
ellipse_df['total_grade'] = np.ceil(ellipse_df['Cohesion'] + 
                                   ellipse_df['Syntax'] + 
                                   ellipse_df['Vocabulary'] + 
                                   ellipse_df['Phraseology'] + 
                                   ellipse_df['Grammar'] + 
                                   ellipse_df['Conventions']).astype(int)

# Calculate min and max values for each scoring dimension
scoring_columns = ['Cohesion', 'Syntax', 'Vocabulary', 'Phraseology', 'Grammar', 'Conventions']
print("Min values for each scoring dimension:")
print(ellipse_df[scoring_columns].min())
print("\nMax values for each scoring dimension:")
print(ellipse_df[scoring_columns].max())

# Calculate min and max for the aggregated total_grade
print(f"\nTotal grade - Min: {ellipse_df['total_grade'].min()}, Max: {ellipse_df['total_grade'].max()}")

Min values for each scoring dimension:
Cohesion       1.0
Syntax         1.0
Vocabulary     1.0
Phraseology    1.0
Grammar        1.0
Conventions    1.0
dtype: float64

Max values for each scoring dimension:
Cohesion       5.0
Syntax         5.0
Vocabulary     5.0
Phraseology    5.0
Grammar        5.0
Conventions    5.0
dtype: float64

Total grade - Min: 6, Max: 30

In [33]:
ellipse_df['task'].value_counts()

task
Independent    3911
Name: count, dtype: int64

In [45]:
ellipse_df['prompt'].value_counts()

prompt
Distance learning                                 297
Career commitment                                 227
Success and failure                               218
Being busy                                        209
Positive attitudes                                178
Impact of technology                              176
Trying something beyond what you have mastered    172
First impressions                                 169
Three-year high school program                    153
Individuality                                     147
Four-day work week                                137
Working with a group or alone                     135
Self-reliance                                     131
Lunch menus                                        93
Influences of character                            92
Extended school day                                90
Year-round school                                  67
Influencing behavior                               64
Cell phones in classrooms                          61
Internships and shadowing                          60
Enjoyable educational activities                   58
Praising student work                              57
Afterschool homework club                          56
Imagination                                        55
Spending time outdoors                             54
Curfews for teenagers                              54
Controlling extracurricular involvement            52
Seeking multiple opinions                          51
Creative arts requirement                          51
Places to visit                                    48
Community service                                  48
Letter to employer                                 45
Cell phones at school                              43
Talents and skills                                 43
Mandatory extracurricular activities               42
Lessons with elementary school students            38
Grades for extracurricular activities              37
Future accomplishments                             35
Benefits of a problem                              33
Learning from the experience of others             30
Benefits of a good attitude                        30
Honesty                                            29
Setting our aim                                    27
Summer projects                                    19
Name: count, dtype: int64

In [48]:
ellipse_test_df = pd.read_csv(r"C:\Users\alvar\Githubs\mentor-eval\data\raw\ellipse\ELLIPSE_Final_github_test.csv")
ellipse_test_df.shape

(2571, 26)

In [52]:
ellipse_rater_df = pd.read_csv(r"C:\Users\alvar\Githubs\mentor-eval\data\raw\ellipse\ellipsis_raw_rater_scores_anon_all_essay.csv")
ellipse_rater_df.shape

(8890, 20)

In [53]:
ellipse_rater_df.head()

,Filename,Text,Rater_1,Overall_1,Cohesion_1,Syntax_1,Vocabulary_1,Phraseology_1,Grammar_1,Conventions_1,Identifying_Info_1,Rater_2,Overall_2,Cohesion_2,Syntax_2,Vocabulary_2,Phraseology_2,Grammar_2,Conventions_2,Identifying_Info_2
0,2021000071.txt,"To the Principal,\r\n\r\nI think that policy 1...",rater_1,3,3,4,4,4,5,3,0,rater_2,3,4,3,3,3,3,3,0
1,2021000501.txt,"Dear, TEACHER_NAME\r\n\r\nI think phone policy...",rater_1,3,3,2,3,3,3,2,0,rater_2,3,4,3,4,3,4,3,0
2,2021000535.txt,"Dear, Principal\r\n\r\nIn my opinion, I think ...",rater_1,3,2,3,2,2,3,3,0,rater_2,3,3,3,4,3,3,4,0
3,2021000667.txt,PHONES\r\n\r\nDear principal students should h...,rater_1,3,2,3,3,3,3,3,0,rater_2,3,3,3,3,3,4,3,0
4,2021000683.txt,phones\r\n\r\ni think phones should be allowed...,rater_1,3,2,3,3,3,3,3,0,rater_2,3,2,2,3,3,3,2,0

## Processed

In [7]:
ellipse_processed_df = pd.read_csv(r"C:\Users\alvar\Githubs\mentor-eval\data\processed\ellipse\ellipse_processed.csv")
ellipse_processed_df.shape

(6482, 14)

In [8]:
ellipse_processed_df.head()

,dataset,exercise_set,question,answer,grade,min_grade,max_grade,subject,exercise_type,isced_level,language,rubric,desired_answer,metadata
0,ellipse,4,Do you agree with Duke Ellington's idea that a...,Imagine if you could prove other people that y...,4.0,1.0,5.0,english,essay_writing,3,english,# English Proficiency Scoring Rubric for Engli...,NaN,"{""gender"": ""Male"", ""grade"": 8, ""race_ethnicity..."
1,ellipse,12,Should high school students take online classe...,I think that students would benefit from learn...,3.0,1.0,5.0,english,essay_writing,3,english,# English Proficiency Scoring Rubric for Engli...,NaN,"{""gender"": ""Male"", ""grade"": 12, ""race_ethnicit..."
2,ellipse,4,Do you agree with Duke Ellington's idea that a...,When a problem is a change you have to let it ...,2.0,1.0,5.0,english,essay_writing,3,english,# English Proficiency Scoring Rubric for Engli...,NaN,"{""gender"": ""Female"", ""grade"": 8, ""race_ethnici..."
3,ellipse,18,Should students be required to maintain a cert...,"Dear, Principal\r\n\r\nIf u change the school ...",3.0,1.0,5.0,english,essay_writing,3,english,# English Proficiency Scoring Rubric for Engli...,NaN,"{""gender"": ""Male"", ""grade"": 8, ""race_ethnicity..."
4,ellipse,22,Is being yourself in a world that is trying to...,The best time in life is when you become yours...,4.0,1.0,5.0,english,essay_writing,3,english,# English Proficiency Scoring Rubric for Engli...,NaN,"{""gender"": ""Male"", ""grade"": 12, ""race_ethnicit..."

In [6]:
print(ellipse_processed_df['rubric'].iloc[0])

# English Proficiency Scoring Rubric for English Language Learners

## Score 5
- Holistic: Native-like facility in the use of language with syntactic variety, appropriate word choice and phrases; well-controlled text organization; precise use of grammar and conventions; rare language inaccuracies that do not impede communication.
- Cohesion: Text organization consistently well controlled using a variety of effective linguistic features such as reference and transitional words and phrases to connect ideas across sentences and paragraphs; appropriate overlap of ideas.
- Syntax: Flexible and effective use of a full range of syntactic structures including simple, compound, and complex sentences; there may be rare minor and negligible errors in sentence formation.
- Vocabulary: Wide range of vocabulary flexibly and effectively used to convey precise meanings; skillful use of topic-related terms and less common words; rare negligible inaccuracies in word use.
- Phraseology: Flexible and effective use of a variety of phrases, such as idioms, collocations, and lexical bundles, to convey precise and subtle meanings; rare minor inaccuracies that are negligible.
- Grammar: Command of grammar and usage with few or no errors.
- Conventions: Consistent use of appropriate conventions to convey meaning; spelling, capitalization, and punctuation errors nonexistent or negligible.

## Score 4
- Holistic: Facility in the use of language with syntactic variety and range of words and phrases; controlled organization; accuracy in grammar and conventions; occasional language inaccuracies that rarely impede communication.
- Cohesion: Organization generally well controlled; a range of cohesive devices used appropriately such as reference and transitional words and phrases to connect ideas; generally appropriate overlap of ideas.
- Syntax: Appropriate use of a variety of syntactic structures, such as simple, compound, and complex sentences; occasional errors or inappropriateness in sentence formation.
- Vocabulary: Sufficient range of vocabulary to allow flexibility and precision; appropriate use of topic-related terms and less common lexical items.
- Phraseology: Appropriate use of a variety of phrases, such as idioms, collocations, and lexical bundles; occasional inaccuracies and colloquialisms.
- Grammar: Minimal errors in grammar and usage.
- Conventions: Generally consistent use of appropriate conventions to convey meaning; spelling, capitalization, and punctuation errors few and not distracting.

## Score 3
- Holistic: Facility limited to the use of common structures and generic vocabulary; organization generally controlled although connection sometimes absent or unsuccessful; errors in grammar and syntax and usage. Communication is impeded by language inaccuracies in some cases.
- Cohesion: Organization generally controlled; cohesive devices used but limited in type; some repetitive, mechanical, or faulty use of cohesion within and/or between sentences and paragraphs.
- Syntax: Simple, compound, and complex syntactic structures present although the range may be limited; some apparent errors in sentence formation, especially in more complex sentences.
- Vocabulary: Minimally adequate range of vocabulary for the topic; no precise use of subtle word meanings; topic-related terms only used occasionally; attempts to use less common vocabulary but with some inaccuracy.
- Phraseology: Evident use of phrases such as idioms, collocations, and lexical bundles but without much variety; some noticeable repetitions and misuses.
- Grammar: Some errors in grammar and usage.
- Conventions: Developing use of conventions to convey meaning; errors in spelling, capitalization, and punctuation that are sometimes distracting.

## Score 2
- Holistic: Inconsistent facility in sentence formation, word choice, and mechanics; organization partially developed but may be missing or unsuccessful. Communication impeded in many instances by language inaccuracies.
- Cohesion: Organization only partially developed with a lack of logical sequencing of ideas; some basic cohesive devices used but with inaccuracy or repetition.
- Syntax: Some sentence variation used; many sentence structure problems.
- Vocabulary: Narrow range of vocabulary to convey basic and elementary meaning; topic-related terms used inappropriately; errors in word formation and word choice that may distort meanings.
- Phraseology: Narrow range of phrases, such as collocations and lexical bundles, used to convey basic and elementary meaning; many repetitions and/or misuses of phrases.
- Grammar: Many errors in grammar and usage.
- Conventions: Variable use of conventions; spelling, capitalization, and punctuation errors frequent and distracting.

## Score 1
- Holistic: A limited range of familiar words or phrases loosely strung together; frequent errors in grammar (including syntax) and usage. Communication impeded in most cases by language inaccuracies.
- Cohesion: No clear control of organization; cohesive devices not present or unsuccessfully used; presentation of ideas unclear.
- Syntax: Pervasive and basic errors in sentence structure and word order that cause confusion; basic sentence errors common.
- Vocabulary: Limited vocabulary often inappropriately used; limited control of word choice and word forms; little attempt to use topic-related terms.
- Phraseology: Memorized chunks of language, or simple phrasal patterns predominate; many repetitions and misuses of phrases.
- Grammar: Errors in grammar and usage throughout.
- Conventions: Minimal use of conventions; spelling, capitalization, and punctuation errors throughout.

In [4]:
len(ellipse_processed_df['exercise_set'].value_counts())

44

# Persuade 2

In [61]:
persuade2_df = pd.read_csv(r"C:\Users\alvar\Githubs\mentor-eval\data\raw\persuade2\persuade_2.0_human_scores_demo_id_github.csv")
persuade2_df.shape

(25996, 14)

In [62]:
persuade2_df.head()

,essay_id_comp,full_text,holistic_essay_score,word_count,prompt_name,task,assignment,source_text,gender,grade_level,ell_status,race_ethnicity,economically_disadvantaged,student_disability_status
0,423A1CA112E2,Phones\n\nModern humans today are always on th...,3,378,Phones and driving,Independent,Today the majority of humans own and operate c...,NaN,M,NaN,NaN,Black/African American,NaN,NaN
1,BC75783F96E3,This essay will explain if drivers should or s...,4,432,Phones and driving,Independent,Today the majority of humans own and operate c...,NaN,M,NaN,NaN,Black/African American,NaN,NaN
2,74C8BC7417DE,Driving while the use of cellular devices\n\nT...,2,179,Phones and driving,Independent,Today the majority of humans own and operate c...,NaN,F,NaN,NaN,White,NaN,NaN
3,A8445CABFECE,Phones & Driving\n\nDrivers should not be able...,3,221,Phones and driving,Independent,Today the majority of humans own and operate c...,NaN,M,NaN,NaN,Black/African American,NaN,NaN
4,6B4F7A0165B9,Cell Phone Operation While Driving\n\nThe abil...,4,334,Phones and driving,Independent,Today the majority of humans own and operate c...,NaN,M,NaN,NaN,White,NaN,NaN

# PTA-SAG 2018

## Raw

(9862, 14)

## Processed

In [7]:
ptasag2018_processed_df = pd.read_csv(r"C:\Users\alvar\Githubs\mentor-eval\data\processed\ptasag2018\ptasag2018_processed.csv")
ptasag2018_processed_df.shape

(9862, 14)

In [8]:
ptasag2018_processed_df.head()

,dataset,exercise_set,question,answer,grade,min_grade,max_grade,subject,exercise_type,isced_level,language,rubric,desired_answer,metadata
0,ptasag2018,1,Qual a diferença entre a célula animal e a cél...,A animal tem núcleo e a vegetal não.,0.0,0.0,3.0,biology,short_answer,3,portuguese,NaN,NaN,NaN
1,ptasag2018,1,Qual a diferença entre a célula animal e a cél...,a célula vegetal tem parede celular a animal não,3.0,0.0,3.0,biology,short_answer,3,portuguese,NaN,NaN,NaN
2,ptasag2018,1,Qual a diferença entre a célula animal e a cél...,uma tem núcleo e a outra não,0.0,0.0,3.0,biology,short_answer,3,portuguese,NaN,NaN,NaN
3,ptasag2018,1,Qual a diferença entre a célula animal e a cél...,animal tem nucleo e a animal n tem nucleo,0.0,0.0,3.0,biology,short_answer,3,portuguese,NaN,NaN,NaN
4,ptasag2018,1,Qual a diferença entre a célula animal e a cél...,"Uma é de seres vivos a outra é de plantas,vege...",1.0,0.0,3.0,biology,short_answer,3,portuguese,NaN,NaN,NaN

In [6]:
ptasag2018_processed_df['exercise_set'].value_counts()

exercise_set
40    678
36    661
44    660
48    657
37    657
50    657
47    656
46    655
38    655
39    655
45    655
49    655
41    654
43    654
42    653
Name: count, dtype: int64

# Summary

In [8]:
mentoreval_combined_df.shape

(57444, 14)

In [3]:
mentoreval_combined_df = pd.read_parquet(r"C:\Users\alvar\Githubs\mentor-eval\data\mentoreval.parquet")
mentoreval_combined_df.head()

,dataset,exercise_set,question,answer,grade,min_grade,max_grade,subject,exercise_type,isced_level,language,rubric,desired_answer,metadata
0,asap,1,"More and more people use computers, but not ev...","Dear local newspaper, I think effects computer...",4,1.0,6.0,english,essay_writing,3,english,## Rubric Guidelines\n\n**Score Point 6**: A w...,None,None
1,asap,1,"More and more people use computers, but not ev...","Dear @CAPS1 @CAPS2, I believe that using compu...",4,1.0,6.0,english,essay_writing,3,english,## Rubric Guidelines\n\n**Score Point 6**: A w...,None,None
2,asap,1,"More and more people use computers, but not ev...","Dear, @CAPS1 @CAPS2 @CAPS3 More and more peopl...",3,1.0,6.0,english,essay_writing,3,english,## Rubric Guidelines\n\n**Score Point 6**: A w...,None,None
3,asap,1,"More and more people use computers, but not ev...","Dear Local Newspaper, @CAPS1 I have found that...",5,1.0,6.0,english,essay_writing,3,english,## Rubric Guidelines\n\n**Score Point 6**: A w...,None,None
4,asap,1,"More and more people use computers, but not ev...","Dear @LOCATION1, I know having computers has a...",4,1.0,6.0,english,essay_writing,3,english,## Rubric Guidelines\n\n**Score Point 6**: A w...,None,None

In [50]:
mentoreval_combined_df['dataset'].value_counts()

dataset
asap2         24728
asap          12977
ptasag2018     9862
ellipse        6482
arasag         2132
mohler         1263
Name: count, dtype: int64

In [51]:
mentoreval_combined_df['subject'].value_counts()

subject
english             44187
biology              9862
cybercrimes          2132
computer_science     1263
Name: count, dtype: int64

In [52]:
mentoreval_combined_df['exercise_type'].value_counts()

exercise_type
essay_writing    44187
short_answer     13257
Name: count, dtype: int64

In [9]:
# Count the number of distinct exercise_sets for each exercise_type
exercise_type_exercise_set_counts = mentoreval_combined_df.groupby('exercise_type')['exercise_set'].nunique()
print(exercise_type_exercise_set_counts)

exercise_type
essay_writing    44
short_answer     81
Name: exercise_set, dtype: int64

In [53]:
mentoreval_combined_df['isced_level'].value_counts()

isced_level
3    54049
6     3395
Name: count, dtype: int64

In [7]:
language_counts = mentoreval_combined_df['language'].value_counts()
language_percentages = mentoreval_combined_df['language'].value_counts(normalize=True) * 100
language_summary = pd.DataFrame({'count': language_counts, 'percentage': language_percentages.round(2)})
print(language_summary)

            count  percentage
language
english     45450       79.12
portuguese   9862       17.17
arabic       2132        3.71

In [ ]:
len(mentoreval_combined_df.groupby(['dataset', 'exercise_set']).size())

In [6]:
mentoreval_combined_df.groupby(['dataset', 'exercise_set']).size()

dataset     exercise_set
arasag      1                 40
            2                 48
            3                 43
            4                 37
            5                 48
            6                 25
            7                 21
            8                 31
            9                 47
            10                47
            11                51
            12                52
            13                48
            14                52
            15                41
            16                54
            17                52
            18                52
            19                54
            20                49
            21                33
            22                51
            23                48
            24                41
            25                45
            26                43
            27                52
            28                50
            29                42
            30                45
            31                37
            32                48
            33                55
            34                54
            35                42
            36                54
            37                37
            38                12
            39                58
            40                48
            41                19
            42                45
            43                44
            44                51
            45                37
            46                46
            47                49
            48                54
asap        1               1783
            2               1800
            3               1726
            4               1771
            5               1805
            6               1800
            7               1569
            8                723
asap2       1               6170
            2               4883
            3               4480
            4               3015
            5               2175
            6               2046
            7               1959
ellipse     1                 97
            2                341
            3                 46
            4                 60
            5                367
            6                 85
            7                 99
            8                 83
            9                 84
            10                92
            11                92
            12               489
            13                91
            14               153
            15               263
            16               229
            17                57
            18                76
            19                54
            20                81
            21               301
            22               253
            23               155
            24                93
            25                92
            26                51
            27                63
            28                70
            29               159
            30                87
            31                84
            32               281
            33                91
            34                54
            35               223
            36                44
            37                91
            38               379
            39                38
            40                61
            41               272
            42               281
            43               217
            44               103
mohler      1                 17
            2                 10
            3                  8
            4                 28
            5                 17
            6                  9
            7                 25
            8                 16
            9                  8
            10                 8
            11                26
            12                26
            13                13
            14                10
            15                22
            16                14
            17                18
            18                19
            19                22
            20                21
            21                21
            22                18
            23                12
            24                25
            25                15
            26                12
            27                15
            28                15
            29                10
            30                17
            31                17
            32                15
            33                18
            34                 4
            35                 8
            36                14
            37                22
            38                 3
            39                22
            40                13
            41                12
            42                21
            43                 6
            44                23
            45                20
            46                27
            47                10
            48                 7
            49                20
            50                 7
            51                25
            52                26
            53                11
            54                 8
            55                23
            56                 6
            57                10
            58                17
            59                17
            60                14
            61                14
            62                14
            63                12
            64                27
            65                17
            66                 8
            67                19
            68                26
            69                28
            70                 4
            71                11
            72                 7
            73                23
            74                 8
            75                10
            76                 7
            77                26
            78                23
            79                25
            80                 5
            81                 6
ptasag2018  1                661
            2                657
            3                655
            4                655
            5                678
            6                654
            7                653
            8                654
            9                660
            10               655
            11               655
            12               656
            13               657
            14               655
            15               657
dtype: int64